### ISSUE TITLE
exception when updating to angular 1.4.9

### ISSUE THREAD

**Issue by igorlino** [dnauck/angular-advanced-searchbox#31]
Hello,

Seems there is a problem with the latest angular. From their release notes, some non-assignable variables are not longer tolerated and an exception is thrown.

```
Error: [CE Error] [$compile:nonassign] Expression 'undefined' used with directive 'nitAdvancedSearchbox' is non-assignable!
http://errors.angularjs.org/1.4.9/$compile/nonassign?p0=undefined&p1=nitAdvancedSearchbox
    at http://localhost:3000/bower_components/angular/angular.js:68:12
    at parentSet (http://localhost:3000/bower_components/angular/angular.js:9092:21)
    at parentValueWatch (http://localhost:3000/bower_components/angular/angular.js:9105:19)
    at Object.regularInterceptedExpression (http://localhost:3000/bower_components/angular/angular.js:14646:16)
    at Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:16087:40)
    at Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:16359:24)
    at done (http://localhost:3000/bower_components/angular/angular.js:10791:47)
    at completeRequest (http://localhost:3000/bower_components/angular/angular.js:10989:7)
    at XMLHttpRequest.requestLoaded (http://localhost:3000/bower_components/angular/angular.js:10930:9) undefined
```

**Comment by jarandaf** [comment]
See #34.

**Comment by dnauck** [comment]
Thanks for the bug report, please test the latest build
