### ISSUE TITLE
What are the dependencies for this directive?

### ISSUE THREAD

**Issue by jondavidford** [dnauck/angular-advanced-searchbox#41]
I'm using angular v1.4.6 and I'm having trouble getting this directive to work. I've followed all the steps on the README to include the directive.

If I don't include jQuery, I get the following error: 

`angular.js:12450 Error: [jqLite:nosel] Looking up elements via selectors is not supported by jqLite! See: http://docs.angularjs.org/api/angular.element
http://errors.angularjs.org/1.4.6/jqLite/nosel
    at http://localhost:9091/javascripts/angular.js:68:12
    at Object.JQLite [as element] (http://localhost:9091/javascripts/angular.js:2780:13)
    at link (http://localhost:9091/javascripts/angular-advanced-searchbox-tpls.min.js:7:5039)
    at http://localhost:9091/javascripts/angular.js:8774:44
    at invokeLinkFn (http://localhost:9091/javascripts/angular.js:8780:9)
    at nodeLinkFn (http://localhost:9091/javascripts/angular.js:8280:11)
    at compositeLinkFn (http://localhost:9091/javascripts/angular.js:7671:13)
    at compositeLinkFn (http://localhost:9091/javascripts/angular.js:7675:13)
    at nodeLinkFn (http://localhost:9091/javascripts/angular.js:8275:24)
    at http://localhost:9091/javascripts/angular.js:8510:13 <input name="searchbox" class="search-parameter-input ng-pristine ng-untouched ng-valid ng-isolate-scope" nit-auto-size-input="" nit-set-focus="setSearchFocus" ng-keydown="keydown($event)" placeholder="{{placeholder}}" ng-focus="focus = true" ng-blur="focus = false" typeahead-on-select="searchQueryTypeaheadOnSelect($item, $model, $label)" typeahead="parameter as parameter.name for parameter in parameters | filter:isUnsedParameter | filter:{name:$viewValue} | limitTo:parametersDisplayLimit" ng-change="searchQueryChanged(searchQuery)" ng-model="searchQuery">`

When I include jQuery in my website, the error goes away, but the autocomplete for parameter suggestions doesn't work. Is jQuery required for this directive? Is a different version of angular required? Have you ever seen this error before?

**Comment by jondavidford** [comment]
Okay, if I use bower I can see the dependencies. Oops.

**Comment by davidson16807** [comment]
The same "jqLite" error appeared to me, despite having both jQuery and angularjs installed. It turned out I needed to load jQuery before angularjs. Figured I'd post it here since it took me a while to figure out.
